### ISSUE TITLE
Create Multiple Particle systems

### ISSUE THREAD

**Issue by Kommandox0** [colini23/Thelaststep#20]
Generate a bunch of particle systems within the Unity project.

**EXPECTED RESULT:**

_Multiple good looking particle system game objects in the Unity Project that represent acurately what they are supposed to represent, for example, fire, lightning, etc._

Implemented in commit 5d89296fb6d34f9ed4d302f545c2b39dc36276a4

**Comment by Melusas** [comment]
esto lo hacia yo garrulu
